# Generated by Django 5.2.6 on 2025-11-02 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tenantinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('future', 'Future'), ('active', 'Active'), ('moving_out', 'Moving Out'), ('moved_out', 'Moved Out')], db_index=True, default='future', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='tenancy_proofs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='users.household')),
            ],
            options={
                'verbose_name': 'tenancy',
                'verbose_name_plural': 'tenancies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this tenancy')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_tenancies', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renters', to='users.tenancy')),
            ],
            options={
                'verbose_name': 'renter',
                'verbose_name_plural': 'renters',
                'ordering': ['-is_primary', 'joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('household',), name='one_active_tenancy_per_household'),
        ),
        migrations.AlterUniqueTogether(
            name='renter',
            unique_together={('tenancy', 'user')},
        ),
    ]
