# Generated by Django 5.2.6 on 2025-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tenancy_renter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='name',
            field=models.CharField(default='Unnamed Tenancy', max_length=255),
        ),
    ]
