# Generated by Django 5.2.6 on 2025-11-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_tenancy_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='checkout_reading',
            field=models.FileField(blank=True, help_text='Checkout reading document for this tenancy', null=True, upload_to='checkout_readings/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='inventory_report',
            field=models.FileField(blank=True, help_text='Inventory report document for this tenancy', null=True, upload_to='inventory_reports/%Y/%m/'),
        ),
    ]
